/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_CmdRegister */

#ifndef _Included_src_CmdRegister
#define _Included_src_CmdRegister
#ifdef __cplusplus
extern "C" {
#endif
#undef src_CmdRegister_serialVersionUID
#define src_CmdRegister_serialVersionUID -3215090123894869218LL
#undef src_CmdRegister_serialVersionUID
#define src_CmdRegister_serialVersionUID -4100238210092549637LL
#undef src_CmdRegister_serialVersionUID
#define src_CmdRegister_serialVersionUID 4974527148936298033LL
#undef src_CmdRegister_PORT
#define src_CmdRegister_PORT 42636L
/*
 * Class:     src_CmdRegister
 * Method:    getLocalTime
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_src_CmdRegister_getLocalTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     src_CmdRegister
 * Method:    getLocalOS
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_src_CmdRegister_getLocalOS
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
